server:
  port: 8084

spring:
  application:
    name: notification
  cloud:
    function:
      definition: orderCreated
    stream:
      function:
        definition: orderCreated
      bindings:
        orderCreated-in-0:
          destination: order.exchange
          group: notification-group
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

#  rabbitmq:
#    host: woodpecker.rmq.cloudamqp.com
#    port: 5672
#    username: kmjkqbni
#    password: NIltQobgxmGHzlayz4Dep5Xuxn_N19wA
#    connection-timeout: 30000
#    virtual-host: kmjkqbni

#rabbitmq:
#  exchange:
#    name: order.exchange
#  queue:
#    name: order.queue
#  routing:
#    key: order.tracking
